// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDTE3HpKUkGahJFn2wRkiinftHO7i0yC8',
    appId: '1:870319072540:web:bd2c8ea597749a8a8186d9',
    messagingSenderId: '870319072540',
    projectId: 'e-bimbingan-6110f',
    authDomain: 'e-bimbingan-6110f.firebaseapp.com',
    storageBucket: 'e-bimbingan-6110f.firebasestorage.app',
    measurementId: 'G-8BJ9FNJ3PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTTqDnHv0OlPEMALCs-LxX74XTqQLgLiQ',
    appId: '1:870319072540:android:37470ab08f1b23ae8186d9',
    messagingSenderId: '870319072540',
    projectId: 'e-bimbingan-6110f',
    storageBucket: 'e-bimbingan-6110f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDTE3HpKUkGahJFn2wRkiinftHO7i0yC8',
    appId: '1:870319072540:web:c48df221cbe8a4af8186d9',
    messagingSenderId: '870319072540',
    projectId: 'e-bimbingan-6110f',
    authDomain: 'e-bimbingan-6110f.firebaseapp.com',
    storageBucket: 'e-bimbingan-6110f.firebasestorage.app',
    measurementId: 'G-ERRQ6KSPSL',
  );
}
